### ISSUE TITLE
Module doesn't install on rustc 1.53.0-nightly

### ISSUE THREAD

**Issue by ChoKyuWon** [jbaublitz/knock-out#11]
Hello. I try to build this repo, but I meet this error:
```
$make V=1
xargo rustc --release --target=x86_64-linux-kernel
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target x86_64-linux-kernel --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "x86_64-linux-kernel". Use `--print target-list` for a list of built-in targets

make: *** [Makefile:21: src/rust.o] Error 101
```
so I change ``x86_64-linux-kernel`` to ``x86_64-unknown-none-linuxkernel`` on Makefile and then it build without error.
However, when I try to install the module, follow error is occur.
```
$sudo insmod parrot.ko
insmod: ERROR: could not insert module parrot.ko: Invalid module format
```

My toolchain and kernel version is here:
```
$rustc --version
rustc 1.53.0-nightly (f82664191 2021-03-21)

$uname -a
Linux kyuwon-systemproductname 5.4.80-2-MANJARO #1 SMP PREEMPT Sat Nov 28 09:58:18 UTC 2020 x86_64 GNU/Linux
```

and module info is here:
```
$modinfo parrot.ko
filename:       /home/kyuwon/knock-out/parrot.ko
license:        GPL v2
depends:        
retpoline:      Y
name:           parrot
vermagic:       5.4.80-2-MANJARO SMP preempt mod_unload modversions 
```

**Comment by jbaublitz** [comment]
I'll look into this, but this seems like a bug somewhere in the Rust build system or compiler. I bumped into this early on in my crate where Rust was emitting relocation symbols unacceptable in the kernel. I just checked, and it's doing it again. See [this issue](https://github.com/rust-lang/rust/issues/57390) for a deeper dive. I may not be able to fix this on my end.

**Comment by jbaublitz** [comment]
Feel free to use the information in my issue linked above and the output of `objdump -r parrot.ko` (the bad symbols you're looking for are `R_X86_64_GOTPCREL`) to file an issue upstream if you'd like this resolved.

**Comment by joroec** [comment]
Since I looked into this, I just append my insights here. Maybe they are helpful for further analysis.
A new toolchain `rustc 1.53.0-nightly (6df26f897 2021-04-20)` is available by now.

Unfortunately, the following illegal relocations are generated:
```shell
$ objdump -r parrot.ko | grep R_X86_64_GOTPCREL
0000000000000036 R_X86_64_GOTPCREL  _ZN4core3num7flt2dec8strategy5grisu12CACHED_POW1017h03fcb65baeeb9113E-0x0000000000000004
00000000000001bf R_X86_64_GOTPCREL  _ZN4core3num7flt2dec8strategy5grisu12CACHED_POW1017h03fcb65baeeb9113E-0x0000000000000004
0000000000000126 R_X86_64_GOTPCREL  _ZN4core3num7flt2dec8strategy5grisu12CACHED_POW1017h03fcb65baeeb9113E-0x0000000000000004
```

It is interesting that the R_X86_64_GOTPCREL relocation is only generated for those tree relocations to the [flt2dec](https://doc.rust-lang.org/beta/src/core/num/dec2flt/mod.rs.html) function. The rest of the core does not seem to be affected.
I cant look into this in more depth by now. However, filing an issue upstream seems to be a good idea, indeed ;-)

**Comment by Mic92** [comment]
I also see it being used for memcpy/memset. It can be reproduced when using `core::ptr::copy`

**Comment by jbaublitz** [comment]
I switched from `xargo` to `build-std` in commit 7bd8f6cf0b40f8480be2b79802008341c42c3784 and this appears to resolve the issue.
