### ISSUE TITLE
compile is ok, but no ko create!

### ISSUE THREAD

**Issue by ygzhu555** [jbaublitz/knock-out#12]
hello, i download this project, after make, but no ko created. 

my kvm:
`
root@yg-test:~/rust/knock-out/src# uname -r
5.4.0-90-generic
root@yg-test:~/rust/knock-out/src# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@yg-test:~/rust/knock-out/src# 
`

rustup show output:
`
root@yg-test:~/rust/knock-out/src# rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.59.0-nightly (db9d361a4 2021-11-28)

`
make：
`
root@yg-test:~/rust/knock-out# make
cargo rustc --release -Z build-std=core,alloc --target=x86_64-unknown-none-linuxkernel
    Updating crates.io index
   Compiling compiler_builtins v0.1.53
   Compiling core v0.0.0 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling spin v0.5.2
   Compiling lazy_static v1.4.0
   Compiling knock-out v0.1.0 (/root/rust/knock-out)
    Finished release [optimized] target(s) in 20.09s
mkdir -p rust_objs
cd rust_objs && ar x ../target/x86_64-unknown-none-linuxkernel/release/librust.a
ld -r -o src/rust.o rust_objs/*.o
`

**no error report when compile, but no ko found in target dir, looking forward to your reply.**

**Comment by jbaublitz** [comment]
Hi @ygzhu555! I am working on addressing this. Likely this module will get ported over to the https://github.com/Rust-for-Linux/linux infrastructure. I will keep you posted.

**Comment by zitudu** [comment]
Try running `make` with root (sudo). It works for me on Fedora.

**Comment by jbaublitz** [comment]
This has taken me a while, but I've migrated to [Rust for Linux support](https://github.com/Rust-for-Linux/linux) in #13. This should resolve the Kbuild problem altogether.

**Comment by jbaublitz** [comment]
Closed by #13
