### ISSUE TITLE
Use safe `coarse_sleep` from upstream

### ISSUE THREAD

**Issue by ojeda** [jbaublitz/knock-out#15]
Since https://github.com/Rust-for-Linux/linux/pull/823 was merged, now there is no need for the `unsafe` block here:

https://github.com/jbaublitz/knock-out/blob/96800f701da4184eb4f685cf15ced7c560b6e022/parrot.rs#L51-L53

**Comment by jbaublitz** [comment]
Closed by be9756553c3cdda6313453d23c082e7715bea6b2
